package com.example.util

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    SETSWANA("tn", "Setswana", "Setswana"),
    ISIZULU("zu", "isiZulu", "isiZulu"),
    AFRIKAANS("af", "Afrikaans", "Afrikaans")
}

object Strings {
    private val englishMap = mapOf(
        "app_tagline" to "Your health, on your terms",
        "login" to "Log In",
        "create_account" to "Create account",
        "register" to "Register",
        "continue_google" to "Continue with Google",
        "email" to "Email",
        "password" to "Password",
        "full_name" to "Full name",
        "preferred_language" to "Preferred language",
        "dashboard" to "Dashboard",
        "medications" to "Medications",
        "log_reading" to "Log reading",
        "find_clinic" to "Find a clinic",
        "settings" to "Settings",
        "today_medication" to "Today's medication",
        "health_log" to "Health log",
        "saved_offline" to "saved offline, will sync",
        "add_medication" to "Add medication",
        "medication_name" to "Medication name",
        "dosage" to "Dosage",
        "frequency" to "Frequency",
        "reminder_times" to "Reminder times",
        "save_medication" to "Save medication",
        "save_reading" to "Save reading",
        "adherence" to "This week's adherence",
        "blood_sugar" to "Blood sugar",
        "blood_pressure" to "Blood pressure",
        "symptom" to "Symptom",
        "when_taken" to "When taken",
        "notes" to "Notes (optional)",
        "offline_save_notice" to "Will save on this device and sync automatically",
        "nearby_clinics" to "Nearby clinics",
        "get_directions" to "Get directions",
        "online_locator" to "Online-only clinic locator",
        "weather_tip" to "Hot day — store insulin below 25°C & stay hydrated",
        "medication_reminders" to "Medication reminders",
        "dark_mode" to "Dark mode",
        "change_password" to "Change password",
        "logout" to "Log out"
    )

    private val setswanaMap = mapOf(
        "app_tagline" to "Botsogo jwa gago, ka melao ya gago",
        "login" to "Kena",
        "create_account" to "Dira akhaonto",
        "register" to "Ikwalise",
        "continue_google" to "Tswelela ka Google",
        "email" to "Emeile",
        "password" to "Lekwalo la sephiri",
        "full_name" to "Leina ka botlalo",
        "preferred_language" to "Puo e e elediwang",
        "dashboard" to "Legae",
        "medications" to "Meriana",
        "log_reading" to "Kwala sekale",
        "find_clinic" to "Batla tleleniki",
        "settings" to "Di-setting",
        "today_medication" to "Meriana ya gompieno",
        "health_log" to "Pekano ya botsogo",
        "saved_offline" to "e bolokilwe ntle le inthanete",
        "add_medication" to "Tsenya molemo",
        "medication_name" to "Leina la molemo",
        "dosage" to "Tekanyo",
        "frequency" to "Kgafetsa",
        "reminder_times" to "Dinako tsa kgopotso",
        "save_medication" to "Boloka molemo",
        "save_reading" to "Boloka sekale",
        "adherence" to "Tiriso ya molemo beke e",
        "blood_sugar" to "Madi a mantsi/sukiri",
        "blood_pressure" to "Kgotlelo ya madi",
        "symptom" to "Matshwao",
        "when_taken" to "E tserwe leng",
        "notes" to "Dintlha (fa o batla)",
        "offline_save_notice" to "E tla bolokwa mo founong e bo e sync fela fa inthanete e bowa",
        "nearby_clinics" to "Ditleleniki tse di gaufi",
        "get_directions" to "Kopa ditaelo tsa tsela",
        "online_locator" to "Mmapa wa inthanete wa tleleniki",
        "weather_tip" to "Letsatsi le le tsididi/gabo — boloka insulin fa tlase ga 25°C",
        "medication_reminders" to "Dikgopotso tsa meriana",
        "dark_mode" to "Monepo wa lefifi",
        "change_password" to "Phetola lekwalo la sephiri",
        "logout" to "Tswaa"
    )

    private val isizuluMap = mapOf(
        "app_tagline" to "Impilo yakho, ngemibandela yakho",
        "login" to "Ngena",
        "create_account" to "Dala i-akhawunti",
        "register" to "Bhalisa",
        "continue_google" to "Qhubeka nge-Google",
        "email" to "I-meyili",
        "password" to "Inkomba-fihlo",
        "full_name" to "Igama eliphelele",
        "preferred_language" to "Ulimi olukhethiwe",
        "dashboard" to "Ikhaya",
        "medications" to "Imithi",
        "log_reading" to "Bhalisa isilinganiso",
        "find_clinic" to "Thola ikliniki",
        "settings" to "Izilungiselelo",
        "today_medication" to "Imithi yanamuhla",
        "health_log" to "Ilogi yezempilo",
        "saved_offline" to "ikulondolozwe ngaphandle kwe-inthanethi",
        "add_medication" to "Faka umuthi",
        "medication_name" to "Igama lomuthi",
        "dosage" to "Isilinganiso",
        "frequency" to "Izikhathi",
        "reminder_times" to "Izikhathi zesikhumbuzo",
        "save_medication" to "Londoloza umuthi",
        "save_reading" to "Londoloza isilinganiso",
        "adherence" to "Ukuthatha imithi kule wiki",
        "blood_sugar" to "Ushukela egazini",
        "blood_pressure" to "Ufutho lwegazi",
        "symptom" to "Izimpawu",
        "when_taken" to "Ithathe nini",
        "notes" to "Amanothi",
        "offline_save_notice" to "Kuzosindiswa kuyo le divaysi bese kuhlanganiswa ngokuzenzakalelayo",
        "nearby_clinics" to "Amakliniki aseduze",
        "get_directions" to "Thola izindlela",
        "online_locator" to "Imephu yekliniki ye-inthanethi",
        "weather_tip" to "Liyashisa namuhla — gcina i-insulin ngaphansi kuka-25°C",
        "medication_reminders" to "Izikhumbuzo zemithi",
        "dark_mode" to "Imo emnyama",
        "change_password" to "Shintsha iphasiwedi",
        "logout" to "Phuma"
    )

    private val afrikaansMap = mapOf(
        "app_tagline" to "Jou gesondheid, op jou terme",
        "login" to "Teken in",
        "create_account" to "Skep rekening",
        "register" to "Registreer",
        "continue_google" to "Gaan voort met Google",
        "email" to "E-pos",
        "password" to "Wagwoord",
        "full_name" to "Volle naam",
        "preferred_language" to "Voorkeurtaal",
        "dashboard" to "Tuisblad",
        "medications" to "Medikasie",
        "log_reading" to "Teken lesing aan",
        "find_clinic" to "Vind kliniek",
        "settings" to "Instellings",
        "today_medication" to "Vandag se medikasie",
        "health_log" to "Gesondheidslogboek",
        "saved_offline" to "vanlyn gestoor, sal sinchroniseer",
        "add_medication" to "Voeg medikasie by",
        "medication_name" to "Medikasie naam",
        "dosage" to "Dosis",
        "frequency" to "Frekwensie",
        "reminder_times" to "Herinneringstye",
        "save_medication" to "Stoor medikasie",
        "save_reading" to "Stoor lesing",
        "adherence" to "Hierdie week se nakoming",
        "blood_sugar" to "Bloedsuiker",
        "blood_pressure" to "Bloeddruk",
        "symptom" to "Simptoom",
        "when_taken" to "Wanneer geneem",
        "notes" to "Notas (opsioneel)",
        "offline_save_notice" to "Sal op hierdie toestel gestoor word en outomaties sinchroniseer",
        "nearby_clinics" to "Nabygeleë klinieke",
        "get_directions" to "Kry aanwysings",
        "online_locator" to "Aanlyn kliniek gids",
        "weather_tip" to "Warm dag — stoor insulien onder 25°C",
        "medication_reminders" to "Medikasie herinneringe",
        "dark_mode" to "Donker tema",
        "change_password" to "Verander wagwoord",
        "logout" to "Meld af"
    )

    fun get(key: String, languageName: String = "English"): String {
        val map = when {
            languageName.equals("Setswana", ignoreCase = true) -> setswanaMap
            languageName.equals("isiZulu", ignoreCase = true) -> isizuluMap
            languageName.equals("Afrikaans", ignoreCase = true) -> afrikaansMap
            else -> englishMap
        }
        return map[key] ?: englishMap[key] ?: key
    }
}
